---
title: "Malaria report"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(flexdashboard)
library("tidyverse")
library("stringr")
library("fuzzyjoin")
library("gganimate")
library("countrycode")
library(plotly)
library(DT)
```



# Initial Analysis

Column {data-width=500, .tabset}
-----------------------------------------------------------------------


### Malaria deaths

```{r}
df_malaria <- read_csv("malaria_deaths.csv") %>%
  setNames(c("country", "code", "year", "deaths"))

df <- tbl_df(df_malaria) %>% top_n(200)

DT::datatable(df, rownames = FALSE, colnames = c("COUNTRY", "CODE", "YEAR", "DEATH COUNT"),
              extensions = 'Buttons',
              options = list(
                dom='Blfrtip',
                buttons = c('print','csv','excel')
              ))
```


### Malaria death incidence

```{r}
df_inc <- read_csv("malaria_inc.csv") %>%
  setNames(c("country", "code", "year", "incidence"))

df1 <- tbl_df(df_inc) %>% top_n(200)

DT::datatable(df1, rownames = FALSE, colnames = c("COUNTRY", "CODE", "YEAR", "INCIDENCE COUNT"),
              extensions = 'Buttons',
              options = list(
                dom='Blfrtip',
                buttons = c('print','csv','excel')
              ))

```

### Malaria death age

```{r}
df_age <- read_csv("malaria_deaths_age.csv") %>%
  setNames(c("country", "code", "year","Age_group" ,"deaths"))

df2 <- tbl_df(df_age) %>% top_n(200)

DT::datatable(df2, rownames = FALSE, colnames = c("COUNTRY", "CODE", "YEAR","AGE GROUP" ,"DEATH COUNT"),
              extensions = 'Buttons',
              options = list(
                dom='Blfrtip',
                buttons = c('print','csv','excel')
              ))

```


Column {data-width=500, .tabset}
-----------------------------------------------------------------------


### Malaria deaths per 100,000 over years in world

```{r}
malaria_country_data <- df_malaria %>%  
    inner_join(maps::iso3166 %>% select(a3,mapname), by = c(code="a3")) %>% 
  mutate(mapname=str_remove(mapname,"\\(.*"))

malaria_map_data <- map_data("world") %>% 
    filter("region" != "Antartica") %>% 
    inner_join(malaria_country_data, by= c(region = "mapname")) 

 chartA <- malaria_map_data %>% ggplot(aes(long,lat, group=group, fill=deaths)) + 
    geom_polygon() + 
    scale_fill_gradient2(low="blue", high="red", midpoint=100) +
    theme_void() +
      labs(fill = "Death per 100,000")

 chartA + coord_fixed(1.4)

```


### Malaria deaths per 100,000 over years in Africa

```{r}
malaria_africa_data <- df_malaria %>% 
    mutate(continent = countrycode(code,"iso3c","continent")) %>% 
    filter(continent=="Africa") %>% 
    inner_join(maps::iso3166 %>% select(a3,mapname), by = c(code="a3")) %>% 
  mutate(mapname=str_remove(mapname,"\\(.*"))

malaria_africa_map <- map_data("world") %>% 
    filter("region" != "Antartica") %>% 
    inner_join(malaria_africa_data, by= c(region = "mapname")) 

malaria_africa_map %>% ggplot(aes(long,lat, group=group, fill=deaths)) + 
    geom_polygon() + 
    scale_fill_gradient2(low="blue", high="red", midpoint=100) +
    theme_void() +
      labs(fill = "Death per 100,000")
```



# Malaria deaths Analysis

Column {data-width=500, .tabset}
-----------------------------------------------------------------------

### Africa animated data Analysis

```{r}
anim_mal <- malaria_africa_map %>%
    ggplot(aes(long,lat, group=group, fill=deaths)) + 
    geom_polygon() + 
    scale_fill_gradient2(low="blue", high="red", midpoint=100) +
    theme_void()  +
    labs(title = "Malaria deaths per 100,000 over years in Africa {frame_time}",
         fill = "Death per 100,000") + 
    transition_time(as.integer(year))

animate(anim_mal, 200, duration=25,  width = 1200, height = 1000, 
        renderer = gifski_renderer("agganim1.gif"))

```


Column {data-width=500, .tabset}
-----------------------------------------------------------------------

### Animated barchat for top 10 Countries

```{r}
mal_formatted <- malaria_africa_data %>%
  group_by(year) %>%
  # The * 1 makes it possible to have non-integer ranks while sliding
  mutate(rank = rank(-deaths),
         Value_rel = deaths/deaths[rank==1],
         Value_lbl = paste0(" ",deaths)) %>%
  group_by(country) %>% 
  filter(rank <=10) %>%
  ungroup()


staticplot = ggplot(mal_formatted, aes(rank, group = country, 
                fill = as.factor(country), color = as.factor(country))) +
  geom_tile(aes(y = deaths/2,
                height = deaths,
                width = 0.9), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(country, " ")), vjust = 0.2, hjust = 1) +
  geom_text(aes(y=deaths,label = Value_lbl, hjust=0)) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
         axis.title.y=element_blank(),
        legend.position="none",
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.grid.major.x = element_line( size=.1, color="grey" ),
        panel.grid.minor.x = element_line( size=.1, color="grey" ),
        plot.title=element_text(size=25, hjust=0.5, face="bold", colour="grey", vjust=-1),
        plot.subtitle=element_text(size=18, hjust=0.5, face="italic", color="grey"),
        plot.caption =element_text(size=8, hjust=0.5, face="italic", color="grey"),
        plot.background=element_blank(),
       plot.margin = margin(2,2, 2, 4, "cm"))

```




```{r}
anim = staticplot + transition_states(year, transition_length = 4, state_length = 1) +
  view_follow(fixed_x = TRUE)  +
  labs(title = 'Malaria deaths per Year : {closest_state}',  
       caption  = "Malaria deaths in 100,000 | Data Source: World Health Organization")

animate(anim, 200, duration=25,  width = 1200, height = 1000, 
        renderer = gifski_renderer("agganim2.gif"))


```



# Additional Analysis


Column {data-width=500}
-----------------------------------------------------------------------

### Malaria deaths by age group in top affected Contries

```{r}

topCountries <- df_age %>%
 filter(country %in% plagued_countries$country) %>%
    filter(year %in% c(2000, 2005, 2010, 2015)) %>%

  group_by( year,Age_group) %>%
  summarise(deaths = sum(deaths)) %>%
  arrange(Age_group, deaths,year) %>%
 
  arrange(desc(deaths,year)) %>%
  ungroup() 


 p<-ggplot(topCountries,aes(x = year, y = deaths,fill=Age_group)) +
 geom_bar(position = position_dodge2(preserve = "single"), stat='identity')+
 theme_minimal()+
   theme(axis.text.x = element_text(angle = 45,hjust = 1))+
     labs(y = "Deaths",
       x = "Top Countries")
 ggplotly(p)
```



### Malaria Deaths Worldwide Trend

```{r}
world=map_data("world")

deaths_per_year_all <- df_malaria %>%
  inner_join(iso3166 %>% select(a3, mapname), by = c(code = "a3")) %>%
  left_join(world, by = c(country = "region"))

deaths_africa_per_year <- deaths_per_year_all %>%
  mutate(
    countrycode(deaths_per_year_all$mapname, 
                origin = "country.name", 
                destination = "continent")) %>%
  rename(continent = `countrycode(...)`) 

    deaths_africa_per_year<-deaths_africa_per_year%>%
  group_by(continent,year) %>%
  summarise(deaths = sum(deaths)) %>%
    ungroup() 


  deaths_africa_per_year<- deaths_africa_per_year  %>% na.omit(continents)
  
 accumulate_by <- function(dat, var) {
  var <- lazyeval::f_eval(var, dat)
  lvls <- plotly:::getLevels(var)
  dats <- lapply(seq_along(lvls), function(x) {
    cbind(dat[var %in% lvls[seq(1, x)], ], frame = lvls[[x]])
  })
  dplyr::bind_rows(dats)
}

topCountries <- deaths_africa_per_year %>% accumulate_by(~year)


 figure <- topCountries %>%
  plot_ly(
    x = ~year, 
    y = ~deaths,
    split = ~continent,
    frame = ~frame, 
    type = 'scatter',
    mode = 'lines', 
    line = list(simplyfy = F)
  )
figure <- figure %>% layout(
  xaxis = list(
    title = "Yaar",
    zeroline = F
  ),
  yaxis = list(
    title = "Deaths",
    zeroline = F
  )
) 
figure <- figure %>% animation_opts(
  frame = 100, 
  transition = 0, 
  redraw = FALSE
)
figure <- figure %>% animation_slider(
  hide = T
)
figure <- figure %>% animation_button(
  x = 1, xanchor = "right", y = 0, yanchor = "bottom"
)


figure
```




Column {data-width=500}
-----------------------------------------------------------------------

### Malaria deaths in top affected Contries

```{r}

topCountries <- malaria %>%
  filter(year %in% c( 2005,2010, 2015))%>%
 filter(country %in% plagued_countries$country) %>%
  group_by( year,country) %>%
  summarise(deaths = sum(deaths)) %>%
  arrange(country, deaths,year) %>%
 
  arrange(desc(deaths)) %>%
  ungroup() %>%
  head(18)

 p<-ggplot(topCountries,aes(x = country, y = deaths,fill=year)) +
 geom_bar(position = position_dodge2(preserve = "single"), stat='identity')+
 theme_minimal()+
   theme(axis.text.x = element_text(angle = 45,hjust = 1))+
     labs(y = "Deaths",
       x = "Top Countries")
 ggplotly(p)


```



### Change in malaria deaths for most impacted countries Over time 

```{r}
topCountries <- df_malaria %>%
  group_by(year, country) %>%
  summarise(deaths = sum(deaths)) %>%
  arrange(country, year) %>%
  filter(country %in% plagued_countries$country) %>%
  ungroup() %>%
  mutate(
    improvement = deaths - lag(deaths)
  ) 

accumulate_by <- function(dat, var) {
  var <- lazyeval::f_eval(var, dat)
  lvls <- plotly:::getLevels(var)
  dats <- lapply(seq_along(lvls), function(x) {
    cbind(dat[var %in% lvls[seq(1, x)], ], frame = lvls[[x]])
  })
  dplyr::bind_rows(dats)
}

topCountries <- topCountries %>% accumulate_by(~year)


 figure <- topCountries %>%
  plot_ly(
    x = ~year, 
    y = ~improvement,
    split = ~country,
    frame = ~frame, 
    type = 'scatter',
    mode = 'lines', 
    line = list(simplyfy = F)
  )
figure <- figure %>% layout(
  xaxis = list(
    title = "Years",
    zeroline = F
  ),
  yaxis = list(
    title = "Improvement Over time",
    zeroline = F
  )
) 
figure <- figure %>% animation_opts(
  frame = 100, 
  transition = 0, 
  redraw = FALSE
)
figure <- figure %>% animation_slider(
  hide = T
)
figure <- figure %>% animation_button(
  x = 1, xanchor = "right", y = 0, yanchor = "bottom"
)

figure
```

